### ISSUE TITLE
Sklearn/XGBoost n threads is hardcoded

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/capice#112]
### Describe the bug
Number of parallel threads used by XGBoost is hardcoded instead of checking n threads available on system:
- https://github.com/molgenis/capice/blob/master/src/molgenis/capice/main_train.py#L146 (refers to https://github.com/molgenis/capice/blob/master/src/molgenis/capice/main_train.py#L39)
- https://github.com/molgenis/capice/blob/master/src/molgenis/capice/main_train.py#L160

### Expected behavior
Either:
A) Value is based on available threads on system. Should be fixable with `n_jobs=-1` (except perhaps on cluster, see below).
B) Set through a command line argument (with value `1` or option A as default).

### Additional context
Pre-1.3.0 versions of XGBoost [have a bug](https://discuss.xgboost.ai/t/n-jobs-1-no-longer-uses-all-cores/1955) and should use something like [this](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/sklearn_parallel.py#L13) instead.

[XGBoost uses cgroup](https://github.com/dmlc/xgboost/pull/7654) to determine if CPU limit should be set lower than actual system resources (when using `n_jobs=-1`). Not sure if this works nicely together with Slurm. Something like [this](https://gist.github.com/kaspermunch/64e11cd21e3953295e149e75bee51733#file-python_multiprocessing_slurm-py-L12) might be needed for that instead. But either way would require some testing on the cluster no matter what solution is chosen.

**Comment by dennishendriksen** [comment]
I prefer B) with 1 as default
