### ISSUE TITLE
Imputing on input instead of derative columns

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/capice#118]
**Is your feature request related to a problem? Please describe.**
Currently imputing is done on the the fields generated after processing the data. This causes a lot of "extra" fields that are imputed and changes in code could result in extra impute fields (instead of the raw input itself). To keep the `impute.json` understandable and small, imputing should be done before splitting columns up into different fields or other mechanisms. The impute json file should not need to know how to deal with the data after all kinds of processing steps done within CAPICE, just how to deal with missing data that is given to CAPICE directly.

**Describe the solution you'd like**
Example of current situation:
`consequence = stop_gained -> is_stop_gained=1 & other 35 consequence columns=0`
The impute json file has a default value for all 36 accepted consequences.

Example of solution:
Impute json has an impute value for when `consequence is null` (if that would even be allowed). Imputing is done on the original data, so that any derivative column doesn't need imputing itself but instead has been created from already imputed data. In scenario's where empty values should be treated as data (f.e. `consequence is null -> is_unknown=1`) , this could be indicated using a specific impute label or removing the impute value and making sure the code knows how to handle every situation.

**Describe alternatives you've considered**
Leaving it as it is. It is a low-priority, but making sure the impute json columns is equal to the input columns instead of all the columns that are derived from the input keeps things more clear when adding/removing features. Additionally, if f.e. unsupported changes are made to certain features (such as including more consequences), this can simply be fixed by a bugfix without needing to create an updated impute json as well.

**Comment by SietsmaRJ** [comment]
Even though the impute json is deprecated, this issue is now relevant with updating the duplicate processing within capice-resources. For that feature to be implemented I need some kind of definition of what features are going to be used in training, so I can subset that on duplicate checking without having to process the features like CAPICE does.
