### ISSUE TITLE
Add GRCh38 gradient boosting tree model

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/capice#13]
as well as pre-computed score files.

**Comment by gujjas** [comment]
Hi, 
Can you please let me know if there's a link available to download Capice scores based on GRCh38 (CADD 1.6)?
Thanks
Shar

**Comment by dennishendriksen** [comment]
We've just released CAPICE v3.0.0 ([release notes](https://github.com/molgenis/capice/releases/download/v3.0.0)) that drops the dependency on CADD. Major advantage is that we have control over which features to add and when to update resulting in better models. The documentation provides details on how to generate your input file for score predictions using Ensembl VEP.

The assets of the release provide download links for GRCh37 and GRCh38 models.
