### ISSUE TITLE
If output file is created while CAPICE is running, file will be overwritten even without -f

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/capice#164]
### Describe the bug
CAPICE validates whether the output file exists during startup, but not when file needs to be written. This can cause issues with files being overwritten without using `-f`, especially as certain functionalities such as training can take several hours. If multiple runs are executed (or would manually create a file) while CAPICE is already running, this will cause the already existing file to be overwritten.

### System information
 - Version: [e.g. 3.0.0]
 - Python version: [e.g. Python3.9.1]
 - Shell: [e.g. ZSH]
 
### How to Reproduce
1. `capice train -i ./resources/train_input.tsv.gz -e ./resources/train_features.json -o ~/Desktop/test1.ubj`
2. while above is still running: `touch ~/Desktop/test1.ubj`

Created empty file will be overwritten by CAPICE even without `-f`.

### Expected behavior
File is not overwritten when no `-f` is used (or a new file is created with a warning if file was created during run of CAPICE).

**Comment by SietsmaRJ** [comment]
Additional note: this is most noticable in train as the training takes the longest. This does not mean that predict and explain do not suffer from the same issue, but to a lesser degree as both those protocols perform way faster.

Error raised seems to be most desirable, even though that might conflict with the time it takes `capice train` to train a new model. Time is lost either way if a trained model is overwritten (but did not exist at the time of starting the train protocol) or with an error raised.
