### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by lqr131115** [molgenis/capice#173]
### Describe the bug
When I type `capice -h`,   I get the error `TypeError: 'type'  object is not subscriptable` 

### System information
 - OS:  Windows subsystem for Linux (ubuntu-18.04)
 - Version: -
 - Python version: 3.8.16
 - Shell: -
 
### How to Reproduce
1. `cd` to dir `capice-5.0.0`
2. Run the command `pip install .`
3. Run the command `capice -h `
4. See error.

### Logs
![image](https://github.com/molgenis/capice/assets/68832962/7ac63e5f-f657-4102-ad76-9b6cd1a17471)

Do I need to perform  any other scripts or command??

**Comment by dennishendriksen** [comment]
Hello @lqr131115,

CAPICE requires Python >=3.10 to run. It looks like you are running Python 3.8.
Alternatively you can use the apptainer/singularity image which can be downloaded [here](https://downloads.molgeniscloud.org/downloads/vip/images/capice-5.1.1.sif).

Greetings,
@dennishendriksen

**Comment by SietsmaRJ** [comment]
I can confirm you need python 3.10 for capice tag 5.0.0, it seems like the setup.py was not properly adjusted (and to this day still isn't) to require python >= 3.10 . We will update the setup.py to require python >= 3.10

**Comment by lqr131115** [comment]
I've already solved that in `python3.10`! Thank for your help! ! 😄
