### ISSUE TITLE
Inquiry about Features Used in CAPICE with CADD Method

### ISSUE THREAD

**Issue by GriffithLin** [molgenis/capice#175]
Hello,

I hope this message finds you well. I am currently using CAPICE and have a question regarding the specific features utilized by the CAPICE method with the CADD (Combined Annotation Dependent Depletion) method.

I would like to understand which features are incorporated into CAPICE when employing the CADD method. Could you please provide information or documentation specifying the features that CAPICE utilizes in conjunction with CADD?

Additionally, if there are any resources or references explaining the feature selection process, I would greatly appreciate it.

Thank you for your assistance!

**Comment by dennishendriksen** [comment]
Hi @GriffithLin,

CAPICE has been under development since the publication located at https://doi.org/10.1186/s13073-020-00775-w. Are you referring to the version related to the publication or a more recent version?

Best regards,
@dennishendriksen

**Comment by GriffithLin** [comment]
Hi @dennishendriksen ,
If possible, I would appreciate information about the feature used in more recent versions. 
Information with the JSON file containing the features desired for training ,which can directly be used for the program woule be very helpful .

Best regards,
@GriffithLin

**Comment by dennishendriksen** [comment]
Are you perhaps looking for https://github.com/molgenis/capice/blob/v5.1.1/resources/train_features.json?

**Comment by GriffithLin** [comment]
the publication said that you have collectted 5 categorical features and 81 numerical variables from VEP  and epigenetic information from ENCODE and the NIH RoadMap project.But in the file "[train_features.json](https://github.com/molgenis/capice/blob/v5.1.1/resources/train_features.json)"you shared only contains 20 features.

**Comment by dennishendriksen** [comment]
The feature set in more recent versions differs from the feature set used to train the model described in the publication. The features used to train the model described in the publication can be derived from https://github.com/molgenis/capice/blob/v1.0/CAPICE_scripts/model_inference.py (I don't think it is available in JSON format).

On a side note: model validation results can be found [here](https://github.com/molgenis/capice-resources/tree/main/validation/).
